### ISSUE TITLE
Error: Unexpected token "SENTENCE" at line 1 

### ISSUE THREAD

**Issue by capnregex** [vowsjs/kyuri#22]
Kyuri is failing to run.. 

$ kyuri features/sample.feature 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unexpected token "SENTENCE" at line 1
    at Object.checkToken (/home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/lib/kyuri/parser.js:405:13)
    at Object.parse (/home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/lib/kyuri/parser.js:390:14)
    at Object.parse (/home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/lib/kyuri/core.js:59:17)
    at /home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/bin/kyuri:91:27
    at Array.forEach (native)
    at /home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/bin/kyuri:85:9
    at Array.forEach (native)
    at Object.<anonymous> (/home/rob/.nvm/v0.6.6/lib/node_modules/kyuri/bin/kyuri:70:6)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
# features/sample.feature

Feature: Addition
  In order to avoid silly mistakes
  As a math idiot
  I want to be told the sum of two numbers

  Scenario: Add two numbers
    Given I have entered 50 into the calculator
    And I have entered 70 into the calculator
    When I press add
    Then the result should be 120 on the screen

**Comment by capnregex** [comment]
Ok, this is really rather odd.. 

I checked out the source, and ran the tests with vows.. works.. 

In order to get the binary to run against the samples, I had to add a symlink from the kyuri back into the node_modules directory so it could find itself 

rob@H86002:~/apps/node/kyuri$ ./bin/kyuri examples/simple.feature 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'kyuri'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/rob/apps/node/kyuri/examples/support/env.js:8:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
rob@H86002:~/apps/node/kyuri$

and I got that working.. 

rob@H86002:~/apps/node/kyuri$ ./bin/kyuri examples
beforeTest event
Feature: Addition
  In order to avoid silly mistakes
  As a math idiot
  I want to be told the sum of two numbers

  Scenario: Add two numbers
Calculator: 50
    Given I have entered 50 into the calculator
Calculator: 70
    And I have entered 70 into the calculator
    When I press add
    Then the result should be 120 on the screen
Feature: Complex Addition
  In order to avoid silly mistakes
  As a math idiot
  I want to be told the sum of two numbers

  Background:
    Given I have a calculator

  Scenario: Add two numbers
beforeBackground event
    Given I have a calculator
    Given I have entered "50" and "75" into the calculator
Calculator: 70
    And I have entered 70 into the calculator
    When I press add
    Then the result should be 120 on the screen

  Scenario Outline: Add three numbers

  Example
beforeBackground event
    Given I have a calculator
Calculator: 10
    Given I have entered 10 into the calculator
Calculator: 20
    And I have entered 20 into the calculator
Calculator: 120
    And I have entered 120 into the calculator
    When I press add
    Then the result should be 150 on the screen
  Example
beforeBackground event
    Given I have a calculator
Calculator: 20
    Given I have entered 20 into the calculator
Calculator: 40
    And I have entered 40 into the calculator
Calculator: 120
    And I have entered 120 into the calculator
    When I press add
    Then the result should be 180 on the screen

  Scenario: Add two numbers
beforeBackground event
    Given I have a calculator
Calculator: 50
    Given I have entered 50 into the calculator
Calculator: 70
    And I have entered 70 into the calculator
    When I press add
    Then the result should be 120 on the screen
afterTest event

4 scenarios (4 passed)
26 steps (11 passed, 15 undefined)
0m0.004s

You can implement step definitions for undefined steps with these snippets:

var Steps = require('kyuri').Steps;

Steps.When(/^I press add$/, function (step) {
    step.pending();
});

Steps.Then(/^the result should be (\d+) on the screen$/, function (step, arg1) {
    step.pending();
});

Steps.Given(/^I have a calculator$/, function (step) {
    step.pending();
});

Steps.Given(/^I have entered "([^"]_?)" and "([^"]_?)" into the calculator$/, function (step, arg1, arg2) {
    step.pending();
});

Steps.export(module);
rob@H86002:~/apps/node/kyuri$

but I am still getting the other error in my project.

**Comment by capnregex** [comment]
Ok, so tabs vs spaces.. 

https://github.com/noblesamurai/cucumis/issues/16

**Comment by capnregex** [comment]
as per the linked issue in cucumis, I changed tabs to spaces, and It works.. 

It would be nice if.. it would either handle either, or give a meaningful error message.
